admin_prompt : |
  Please select an option:

  1.  view all the products
  2.  add a new product
  3.  update an existing product
  4.  delete existing product
  5.  view all placed orders
  6.  logout

  Enter your choice: 

customer_prompt : |
  Please Select an Option:

  1: view the list of available products
  2: select from existing products and place order
  3: check wallet status
  4: update wallet status
  5: logout from account

  Enter your choice: 

update_product_prompt : |
  Please select an option:

  1. update product name
  2. update product quantity 
  3. update product price

  Enter your choice: 

welcome : '************Welcome to Online Grocery Store************ \n \n'

database_name : grocery.db

ask_for_login_signup : |
  Please Select an option:

  1. LOGIN
  2. SIGNUP
  3. QUIT

  Enter: 

enter_valid_prompt : Enter Valid Choice!!!

signup_success : Successfully Signed Up...

login_success : Successfully Logged In...

credential_warning : Please Enter Valid Credentials

admin_role_choice : |
  1. LOGIN as Admin
  2. LOGIN as Customer 

pwd_warning : Enter Strong Password!!

enter_wallet_amount :  'Enter your wallet status: '

ask_for_pwd : 'Enter your password: '

ask_for_name : 'Enter your name: '

ask_for_email : 'Enter your email: '

attempts_left_warning : ' attempts left !!! '

add_amount_to_wallet : 'Enter the amount you want to add to wallet: '

ask_for_update : |
  Insufficient Amount in wallet....

  Do you want to update it?

  1. Yes
  2. No

  Your choice: 

ask_prod_name : 'Enter product name: '

o_id : 1

ask_prod_price : 'Enter product price: '

ask_prod_quan : 'Enter product quantity: '

ask_prod_id : 'Enter product id:  '

enter_new_prod_name : 'Enter new name of product: '

enter_new_prod_quan : 'Enter new quantity of product: '

enter_new_prod_price : 'Enter new price of product: '

prod_id_for_delete : 'Enter the product id you want to delete: '

select_valid_product : 'Select Valid Product! '

select_product_prompt : |
  Please select an option:

  1. Select products
  2. Exit

  Enter: 

ask_to_place_order : |
  Do you want to place order...

  1. Yes
  2. No

  Enter: 
  
wallet_money : Wallet Money

items_remain : Only {number} items are remaining. 

add_sufficient_money: Add atleast Rs.{money} to wallet.

prod_does_not_exist : No such product exists!!! 